### PR TITLE
Update skeleton app for PHP 7.2 7.3 7.4

### PR DESCRIPTION
**Pull request by phil-davis**
The current (or near future) objective will be to support PHP 7.2 7.3 and 7.4.

Might as well update the "skeleton" files here, just in case anyone uses this as a reference.

### CODE REVIEW

**Comment by phil-davis** [comment]
Note: this repo still references `sabre-cs-fixer` from https://github.com/sabre-io/cs which is archived, and is old (more modern PHP 7.,3 and 7.4 complain about old code in the `php-cs-fixer` that it depends on)

What is supposed to be the current code standard checker used in sabre-io repos?

**Comment by staabm** [comment]
> Note: this repo still references `sabre-cs-fixer` from https://github.com/sabre-io/cs which is archived, and is old (more modern PHP 7.,3 and 7.4 complain about old code in the `php-cs-fixer` that it depends on)
> 
> What is supposed to be the current code standard checker used in sabre-io repos?

We use regular php-cs-fixer, see https://github.com/sabre-io/dav/pull/1092

**Comment by staabm** [comment]
Never used the skeleton. Not sure its popular. But updating it still makes sense, so thanks

**Comment by staabm** [comment]
It seems this package is not even published on packagist:
https://packagist.org/?query=sabre%2Fskel

Does it have a value for someone or should we just achrive it?

**Comment by evert** [comment]
The original goal of this repo was to serve as a template for future sabre/* libraries. Feel free to archive it.

**Comment by phil-davis** [comment]
Yes, it's not something to actually publish - just a place to copy from.
I will merge this just so things are a bit more up-to-date.
I might make a PR for the fixer also, later.

**Pull request merged**
